-- Esquema completo do Hub Action para PostgreSQL (equivalente ao estado final
-- das migrações 0001–0008 do SQLite). Regras:
-- - timestamps são TEXT em ISO 8601 UTC, sempre gravados pela aplicação
--   (nunca por função do banco) — igual ao SQLite;
-- - booleanos são INTEGER 0/1, igual ao SQLite;
-- - ids são IDENTITY; a aplicação usa `INSERT ... RETURNING id`.
-- Novas migrações precisam existir nas DUAS pastas (migrations/sqlite e
-- migrations/postgres) com o mesmo nome de arquivo.

CREATE TABLE companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  timezone TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
  business_hours TEXT NOT NULL DEFAULT '{"mon":{"start":"09:00","end":"18:00"},"tue":{"start":"09:00","end":"18:00"},"wed":{"start":"09:00","end":"18:00"},"thu":{"start":"09:00","end":"18:00"},"fri":{"start":"09:00","end":"18:00"},"sat":null,"sun":null}',
  sla_first_response_minutes INTEGER NOT NULL DEFAULT 15,
  plan TEXT NOT NULL DEFAULT 'DEMONSTRACAO' CHECK (plan IN ('DEMONSTRACAO', 'PILOTO', 'ATIVO')),
  suspended INTEGER NOT NULL DEFAULT 0,
  plan_notes TEXT
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  is_platform_admin INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE memberships (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('COMPANY_ADMIN', 'AGENT')),
  created_at TEXT NOT NULL,
  UNIQUE (user_id, company_id)
);
CREATE INDEX idx_memberships_user ON memberships(user_id);
CREATE INDEX idx_memberships_company ON memberships(company_id);

CREATE TABLE contacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE (company_id, phone)
);
CREATE INDEX idx_contacts_company ON contacts(company_id);

CREATE TABLE conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  contact_id INTEGER NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  channel TEXT NOT NULL DEFAULT 'SIMULADO',
  mode TEXT NOT NULL DEFAULT 'AUTOMATICO' CHECK (mode IN ('AUTOMATICO', 'MANUAL')),
  status TEXT NOT NULL DEFAULT 'AUTO' CHECK (status IN ('AUTO', 'AGUARDANDO_HUMANO', 'HUMANO', 'AGUARDANDO_CLIENTE', 'ENCERRADO')),
  assigned_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  pending_context TEXT
);
CREATE INDEX idx_conversations_company ON conversations(company_id);

CREATE TABLE messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  author_type TEXT NOT NULL CHECK (author_type IN ('CLIENTE', 'ROBO', 'HUMANO', 'AUTOMACAO', 'DESCONHECIDO')),
  author_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  body TEXT NOT NULL,
  send_status TEXT NOT NULL DEFAULT 'ENVIADA' CHECK (send_status IN ('ENVIADA', 'FALHOU')),
  created_at TEXT NOT NULL,
  external_id TEXT,
  delivery_status TEXT CHECK (delivery_status IN ('ENTREGUE', 'LIDA'))
);
CREATE INDEX idx_messages_conversation ON messages(conversation_id);
CREATE UNIQUE INDEX idx_messages_external_id ON messages(external_id) WHERE external_id IS NOT NULL;

CREATE TABLE wait_episodes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  started_at TEXT NOT NULL,
  ended_at TEXT,
  ended_reason TEXT CHECK (ended_reason IN ('RESPOSTA_HUMANA', 'ENCERRADO_SEM_RESPOSTA')),
  created_at TEXT NOT NULL,
  ended_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  trigger_type TEXT CHECK (trigger_type IN ('OPCAO_3', 'BOTAO_PLATAFORMA', 'MENSAGEM_ROBO', 'EVENTO_PLATAFORMA', 'TEXTO_LIVRE', 'MODO_MANUAL')),
  trigger_evidence TEXT
);
CREATE INDEX idx_wait_episodes_conversation ON wait_episodes(conversation_id);

CREATE TABLE pipeline_stages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  position INTEGER NOT NULL,
  is_won INTEGER NOT NULL DEFAULT 0,
  is_lost INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);
CREATE INDEX idx_pipeline_stages_company ON pipeline_stages(company_id);

CREATE TABLE opportunities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  contact_id INTEGER NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  stage_id INTEGER NOT NULL REFERENCES pipeline_stages(id) ON DELETE RESTRICT,
  title TEXT NOT NULL,
  value_cents INTEGER NOT NULL DEFAULT 0,
  responsible_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  scheduled_at TEXT,
  lost_reason TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  closed_at TEXT
);
CREATE INDEX idx_opportunities_company ON opportunities(company_id);
CREATE INDEX idx_opportunities_stage ON opportunities(stage_id);

CREATE TABLE whatsapp_connections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  phone_number_id TEXT NOT NULL UNIQUE,
  waba_id TEXT,
  display_phone_number TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  environment TEXT NOT NULL DEFAULT 'TESTE' CHECK (environment IN ('TESTE', 'PRODUCAO')),
  last_verified_at TEXT,
  last_verified_ok INTEGER,
  last_verified_detail TEXT
);
CREATE INDEX idx_whatsapp_connections_company ON whatsapp_connections(company_id);

CREATE TABLE access_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('CONVITE', 'REDEFINICAO')),
  token_hash TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL,
  company_id INTEGER REFERENCES companies(id) ON DELETE CASCADE,
  role TEXT CHECK (role IN ('COMPANY_ADMIN', 'AGENT')),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  detail TEXT,
  ip TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX idx_audit_log_company ON audit_log(company_id, id);

-- expires_at em milissegundos Unix: precisa de BIGINT (INTEGER de 32 bits estoura).
CREATE TABLE sessions (
  sid TEXT PRIMARY KEY,
  sess TEXT NOT NULL,
  expires_at BIGINT NOT NULL
);
CREATE INDEX idx_sessions_expires ON sessions(expires_at);
