-- Command Center: Meta Ads + Google Ads (somente leitura) + atribuição
-- CRM + inteligência (metas, alertas, feedback de conversão preparado).
-- Só ADD COLUMN / CREATE TABLE — nada é apagado ou recriado. Ver bi.ts,
-- attribution.ts, marketingModels.ts, marketingSync.ts, alerts.ts.

-- --- Atribuição no contato (primeiro toque) ---------------------------------
-- source: META_ADS | GOOGLE_ADS | ORGANICO | INSTAGRAM | SITE | INDICACAO | OUTROS | DESCONHECIDA
-- attribution_confidence: CONFIRMADA (id oficial: ctwa_clid/gclid/fbclid/ids de campanha)
--   | PROVAVEL (só UTM/regra consistente) | NAO_ATRIBUIDA (sem evidência)
ALTER TABLE contacts ADD COLUMN source TEXT NOT NULL DEFAULT 'DESCONHECIDA';
ALTER TABLE contacts ADD COLUMN attribution_confidence TEXT NOT NULL DEFAULT 'NAO_ATRIBUIDA' CHECK (attribution_confidence IN ('CONFIRMADA', 'PROVAVEL', 'NAO_ATRIBUIDA'));
ALTER TABLE contacts ADD COLUMN attribution_provider TEXT;
ALTER TABLE contacts ADD COLUMN utm_source TEXT;
ALTER TABLE contacts ADD COLUMN utm_medium TEXT;
ALTER TABLE contacts ADD COLUMN utm_campaign TEXT;
ALTER TABLE contacts ADD COLUMN utm_content TEXT;
ALTER TABLE contacts ADD COLUMN utm_term TEXT;
ALTER TABLE contacts ADD COLUMN fbclid TEXT;
ALTER TABLE contacts ADD COLUMN gclid TEXT;
ALTER TABLE contacts ADD COLUMN gbraid TEXT;
ALTER TABLE contacts ADD COLUMN wbraid TEXT;
ALTER TABLE contacts ADD COLUMN ctwa_clid TEXT;
ALTER TABLE contacts ADD COLUMN external_campaign_id TEXT;
ALTER TABLE contacts ADD COLUMN external_adset_id TEXT;
ALTER TABLE contacts ADD COLUMN external_ad_id TEXT;
ALTER TABLE contacts ADD COLUMN referral_headline TEXT;
ALTER TABLE contacts ADD COLUMN referral_source_url TEXT;
ALTER TABLE contacts ADD COLUMN attributed_at TEXT;
CREATE INDEX idx_contacts_company_source ON contacts(company_id, source);
CREATE INDEX idx_contacts_company_campaign ON contacts(company_id, external_campaign_id);

-- --- Etapas do funil com significado (qualificado / compareceu) -------------
ALTER TABLE pipeline_stages ADD COLUMN is_qualified INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pipeline_stages ADD COLUMN is_attended INTEGER NOT NULL DEFAULT 0;
UPDATE pipeline_stages SET is_qualified = 1 WHERE name = 'Qualificado';

ALTER TABLE opportunities ADD COLUMN qualified_at TEXT;
ALTER TABLE opportunities ADD COLUMN attended_at TEXT;
-- Histórico: oportunidade que já está numa etapa qualificada/ganha passou pela
-- qualificação — usa a última atualização como referência (única data disponível).
UPDATE opportunities SET qualified_at = updated_at
 WHERE qualified_at IS NULL AND stage_id IN (SELECT id FROM pipeline_stages WHERE is_qualified = 1 OR is_won = 1);
CREATE INDEX idx_opportunities_company_created ON opportunities(company_id, created_at);

-- --- Permissão de mídia paga para atendente (capability, sem novo papel) ----
ALTER TABLE memberships ADD COLUMN can_view_marketing INTEGER NOT NULL DEFAULT 0;

-- --- Conexões OAuth (uma por "usuário da Meta/Google" que autorizou) --------
-- company_id é NULL: a conexão é da Hub Action; as CONTAS é que são vinculadas
-- a empresas (marketing_accounts.company_id). Tokens sempre cifrados.
CREATE TABLE marketing_connections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL CHECK (provider IN ('META', 'GOOGLE')),
  status TEXT NOT NULL DEFAULT 'CONECTADA' CHECK (status IN ('CONECTADA', 'EXPIRADA', 'ERRO', 'REVOGADA', 'RECONEXAO_NECESSARIA')),
  external_user_id TEXT,
  display_name TEXT,
  scopes TEXT,
  encrypted_access_token TEXT,
  encrypted_refresh_token TEXT,
  token_expires_at TEXT,
  last_sync_at TEXT,
  last_success_at TEXT,
  last_error_sanitized TEXT,
  created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE marketing_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connection_id INTEGER NOT NULL REFERENCES marketing_connections(id) ON DELETE CASCADE,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  provider TEXT NOT NULL CHECK (provider IN ('META', 'GOOGLE')),
  external_account_id TEXT NOT NULL,
  name TEXT,
  currency TEXT,
  timezone TEXT,
  account_status TEXT,
  is_manager INTEGER NOT NULL DEFAULT 0,
  login_customer_id TEXT,
  sync_enabled INTEGER NOT NULL DEFAULT 0,
  linked_at TEXT,
  last_sync_at TEXT,
  last_success_at TEXT,
  last_error_sanitized TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (provider, external_account_id)
);
CREATE INDEX idx_marketing_accounts_company ON marketing_accounts(company_id);

CREATE TABLE marketing_campaigns (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  account_id INTEGER NOT NULL REFERENCES marketing_accounts(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  external_id TEXT NOT NULL,
  name TEXT NOT NULL,
  status TEXT,
  objective TEXT,
  campaign_type TEXT,
  daily_budget_cents INTEGER,
  lifetime_budget_cents INTEGER,
  currency TEXT,
  start_date TEXT,
  end_date TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (account_id, external_id)
);
CREATE INDEX idx_marketing_campaigns_company ON marketing_campaigns(company_id);

CREATE TABLE marketing_ad_groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  account_id INTEGER NOT NULL REFERENCES marketing_accounts(id) ON DELETE CASCADE,
  campaign_id INTEGER NOT NULL REFERENCES marketing_campaigns(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  external_id TEXT NOT NULL,
  name TEXT NOT NULL,
  status TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (account_id, external_id)
);

CREATE TABLE marketing_ads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  account_id INTEGER NOT NULL REFERENCES marketing_accounts(id) ON DELETE CASCADE,
  campaign_id INTEGER NOT NULL REFERENCES marketing_campaigns(id) ON DELETE CASCADE,
  ad_group_id INTEGER REFERENCES marketing_ad_groups(id) ON DELETE SET NULL,
  provider TEXT NOT NULL,
  external_id TEXT NOT NULL,
  name TEXT NOT NULL,
  status TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (account_id, external_id)
);

-- Métricas diárias normalizadas (BI). dimension_key = nível + ids externos —
-- chave de idempotência da sincronização junto com metric_date.
CREATE TABLE marketing_metrics_daily (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  provider TEXT NOT NULL,
  account_id INTEGER NOT NULL REFERENCES marketing_accounts(id) ON DELETE CASCADE,
  campaign_id INTEGER REFERENCES marketing_campaigns(id) ON DELETE CASCADE,
  ad_group_id INTEGER REFERENCES marketing_ad_groups(id) ON DELETE CASCADE,
  ad_id INTEGER REFERENCES marketing_ads(id) ON DELETE CASCADE,
  level TEXT NOT NULL CHECK (level IN ('ACCOUNT', 'CAMPAIGN', 'ADGROUP', 'AD')),
  dimension_key TEXT NOT NULL,
  metric_date TEXT NOT NULL,
  currency TEXT,
  spend_cents INTEGER NOT NULL DEFAULT 0,
  impressions INTEGER,
  reach INTEGER,
  frequency REAL,
  clicks INTEGER,
  link_clicks INTEGER,
  platform_conversations INTEGER,
  platform_leads INTEGER,
  platform_conversions REAL,
  platform_conversion_value_cents INTEGER,
  raw_metrics_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (dimension_key, metric_date)
);
CREATE INDEX idx_mmd_company_date ON marketing_metrics_daily(company_id, metric_date);
CREATE INDEX idx_mmd_campaign_date ON marketing_metrics_daily(campaign_id, metric_date);
CREATE INDEX idx_mmd_account_date ON marketing_metrics_daily(account_id, metric_date);
CREATE INDEX idx_mmd_provider_date ON marketing_metrics_daily(provider, metric_date);

CREATE TABLE marketing_sync_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  provider TEXT NOT NULL,
  account_id INTEGER REFERENCES marketing_accounts(id) ON DELETE SET NULL,
  trigger_kind TEXT NOT NULL CHECK (trigger_kind IN ('MANUAL', 'AUTO', 'INICIAL')),
  status TEXT NOT NULL CHECK (status IN ('RODANDO', 'OK', 'ERRO')),
  started_at TEXT NOT NULL,
  finished_at TEXT,
  window_from TEXT,
  window_to TEXT,
  processed_count INTEGER NOT NULL DEFAULT 0,
  error_sanitized TEXT,
  created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_sync_runs_account ON marketing_sync_runs(account_id, id);

-- OAuth state (anti-CSRF) + PKCE verifier, uso único, expira em 15 min.
CREATE TABLE oauth_states (
  state TEXT PRIMARY KEY,
  provider TEXT NOT NULL,
  created_by_user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  code_verifier TEXT,
  expires_at TEXT NOT NULL,
  used_at TEXT
);

-- --- Metas por empresa (uma linha por empresa; mês corrente) ----------------
CREATE TABLE company_goals (
  company_id INTEGER PRIMARY KEY REFERENCES companies(id) ON DELETE CASCADE,
  revenue_cents INTEGER,
  new_customers INTEGER,
  leads INTEGER,
  qualified_leads INTEGER,
  appointments INTEGER,
  attendances INTEGER,
  max_cac_cents INTEGER,
  max_cpl_cents INTEGER,
  min_roas REAL,
  planned_monthly_spend_cents INTEGER,
  updated_at TEXT NOT NULL
);

-- --- Alertas (regras configuráveis + ocorrências) ---------------------------
CREATE TABLE alert_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER REFERENCES companies(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  threshold REAL NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (company_id, kind)
);

CREATE TABLE alerts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('CRITICO', 'ATENCAO', 'OPORTUNIDADE', 'INFORMACAO')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  metric TEXT,
  current_value TEXT,
  reference_value TEXT,
  status TEXT NOT NULL DEFAULT 'ABERTO' CHECK (status IN ('ABERTO', 'EM_ANALISE', 'RESOLVIDO', 'IGNORADO')),
  assignee_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  dedupe_key TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  resolved_at TEXT,
  UNIQUE (company_id, dedupe_key)
);
CREATE INDEX idx_alerts_company_status ON alerts(company_id, status, id);

-- --- Feedback de conversão (Meta CAPI / Google offline) — só arquitetura ----
-- Nada é enviado: sender desativado até haver credenciais e ativação explícita.
CREATE TABLE conversion_feedback_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('META', 'GOOGLE')),
  enabled INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL,
  UNIQUE (company_id, provider)
);

CREATE TABLE conversion_feedback_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('META', 'GOOGLE')),
  contact_id INTEGER REFERENCES contacts(id) ON DELETE SET NULL,
  opportunity_id INTEGER REFERENCES opportunities(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  event_time TEXT NOT NULL,
  value_cents INTEGER,
  currency TEXT,
  source TEXT,
  attribution_confidence TEXT,
  external_event_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDENTE' CHECK (status IN ('PENDENTE', 'VALIDADO', 'ENVIADO', 'ACEITO', 'REJEITADO', 'DESATIVADO')),
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  sent_at TEXT,
  created_at TEXT NOT NULL,
  UNIQUE (company_id, provider, external_event_id)
);
